---
apiVersion: "v1"
kind: "Template"
metadata:
  annotations:
    fabric8.testing2/summary: "Camel route using Servlet deployed as WAR"
    description: "Camel route using Servlet deployed as WAR"
    fabric8.testing2/iconUrl: "img/icons/camel.svg"
  labels: {}
  name: "testing2"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      servicepath: "/hello"
      fabric8.io/iconUrl: "img/icons/camel.svg"
    labels:
      provider: "fabric8"
      project: "testing2"
      version: "1.0-SNAPSHOT"
      group: "quickstarts"
    name: "testing2"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "testing2"
      provider: "fabric8"
      group: "quickstarts"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/iconUrl: "img/icons/camel.svg"
    labels:
      provider: "fabric8"
      project: "testing2"
      version: "1.0-SNAPSHOT"
      group: "quickstarts"
    name: "testing2"
  spec:
    replicas: 1
    selector:
      provider: "fabric8"
      project: "testing2"
      version: "1.0-SNAPSHOT"
      group: "quickstarts"
    template:
      metadata:
        annotations: {}
        labels:
          provider: "fabric8"
          project: "testing2"
          version: "1.0-SNAPSHOT"
          group: "quickstarts"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/testing2:1.0-SNAPSHOT"
          name: "testing2"
          ports:
          - containerPort: 8080
            name: "http"
          - containerPort: 8778
            name: "jolokia"
          readinessProbe:
            httpGet:
              httpHeaders: []
              path: "/"
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 30
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
